function delta=getDelta(S,t,T,x,D)

% Get the delta value from delta matrix generated by MyCallPutDelta
% 
% Pre:
% S: underlying price
% t: time to maturity (i.e. T-t)
% T: maturity
% x: discretization of S, returned by MyCallPutDelta
% D: delta matrix returned by MyCallPutDelta
% 
% Post:
% delta: delta of the option at price=S, time to maturity=t, calculated by interpolation

Nx=length(x)-1;
Nt=size(D,2)-1;
if t<0 || t>T
    disp('please enter a valid time')
    delta=-10;
elseif S<=x(2)
    delta=D(1,1);
elseif S>=x(Nx)
    delta=D(Nx-1,1);
elseif t==0
    i=3;
    while S>x(i)
        i=i+1;
    end
    a=(S-x(i-1))/(x(i)-x(i-1));
    delta=(1-a)*D(i-2,1)+a*D(i-1,1);
else
    i=3;
    while S>x(i)
        i=i+1;
    end
    a=(S-x(i-1))/(x(i)-x(i-1));
    j=ceil(t*Nt/T);
    b=t*Nt/T+1-j;
    delta=(1-b)*((1-a)*D(i-2,j)+a*D(i-1,j))+b*((1-a)*D(i-2,j+1)+a*D(i-1,j+1));
end
    